---
- name: Delete Triton From the Workers
  hosts: Workers

  tasks:
    
    - name: Delete triton directory 
      ansible.builtin.file:
        path: '{{triton_install_dir}}/tritonserver'
        state: absent 
      become: yes

    - name: Delete symlinks 
      ansible.builtin.file:
        path: /home/iloudaros/tritonserver
        state: absent 
      become: yes
  
    - name: Delete flag file for triton
      ansible.builtin.file:
        path: /ansible/flags/triton_installed.flag
        state: absent
      become: yes

    - name: Delete flag file for model repository
      ansible.builtin.file:
        path: /ansible/flags/model_repository_installed.flag
        state: absent
      become: yes


