---
- name: Download and distribute file to worker nodes
  hosts: Workers
  gather_facts: no

  tasks:

    - name: Check the flags 
      stat:
        path: /ansible/flags/triton_installed.flag
      register: flag

    - name: Download - Copy - Unarchive
      block:
        - name: Download Release 2.19
          delegate_to: localhost
          run_once: yes
          get_url:
            url: https://github.com/triton-inference-server/server/releases/download/v2.19.0/tritonserver2.19.0-jetpack4.6.1.tgz
            dest: ~/tritonserver2_19.tgz       
          async: 1000
          poll: 0
          register: download2_19

        - name: Download Release 2.34
          delegate_to: localhost
          run_once: yes
          get_url:
            url: https://github.com/triton-inference-server/server/releases/download/v2.34.0/tritonserver2.34.0-jetpack5.1.tgz
            dest: ~/tritonserver2_34.tgz
          async: 1000
          poll: 0
          register: download2_34

        - name: Wait for file downloads to complete
          delegate_to: localhost
          async_status:
            jid: "{{ item.ansible_job_id }}"
          register: job_result
          until: job_result.finished
          retries: 10
          delay: 10
          loop: 
            - "{{ download2_19 }}"
            - "{{ download2_34 }}"

        - name: Triton Server Downloaded
          debug:
            msg: "Triton Server has been downloaded"
            
        - name: Copy Triton to the workers
          copy:
            src: ~/tritonserver{{triton_version}}.tgz
            dest: '{{triton_install_dir}}/tritonserver.tgz'
          register: copy
          become: yes

        - name: Ensure directory exists
          file:
            path: '{{triton_install_dir}}/tritonserver'
            state: directory
          become: yes

        
        - name: Unarchive tritonserver.tgz on the workers
          ansible.builtin.unarchive:
            src: '{{triton_install_dir}}/tritonserver.tgz'
            dest: '{{triton_install_dir}}/tritonserver'
            remote_src: yes
          register: unarchive
          become: yes

        - name: Delete tgz file on workers
          ansible.builtin.file:
            path: '{{triton_install_dir}}/tritonserver.tgz'
            state: absent
          become: yes

        - name: Create symlink on workers if install dir is different than /home/iloudaros
          ansible.builtin.file:
            src: '{{triton_install_dir}}/tritonserver'
            dest: /home/iloudaros/tritonserver
            state: link
          when: triton_install_dir != '/home/iloudaros'
          become: yes 

      when: not flag.stat.exists

    - name: Leave a flag file
      block:
        - ansible.builtin.file:
            path: /ansible/flags
            state: directory
            mode: '0755'

        - ansible.builtin.file:
            path: /ansible/flags/triton_installed.flag
            state: touch
      become: yes


    

