---
- name: Copy the environment to the Workers
  hosts: NX
  gather_facts: no

  tasks:
    - name: Copy the environment to the Workers
      copy:
        src: /home/louduser/LoudVA/.environment 
        dest: /home/iloudaros/LoudVA/
      become: yes
    
    