---
- name: Copy the environment to the Workers
  hosts: Workers
  gather_facts: no

  tasks:
    - name: Copy the environment to the Workers
      copy:
        src: /home/iloudaros/Desktop/LoudVA/.environment 
        dest: /home/iloudaros/Desktop/LoudVA/
      become: yes
    
    