---
- name: Start WorkerController
  hosts: Workers
  gather_facts: no
  become: yes

  tasks:

    - name: Check if the WorkerController is already running
      ansible.builtin.stat:
        path: /tmp/ansible/flags/WorkerController_running.flag
      register: WorkerController_running


    - name: Ensure the set script is executable
      file:
        path: /home/iloudaros/LoudVA/scripts/shell/set_frequency.sh
        mode: '0755'
    
    - name: Ensure the get script is executable
      file:
        path: /home/iloudaros/LoudVA/scripts/shell/get_frequency.sh
        mode: '0755'

    - name: Start Flask app
      shell: |
        screen -dmS WorkerController bash -c 'export FLASK_APP=/home/iloudaros/LoudVA/WorkerController/WorkerController.py && flask run --host=0.0.0.0 --port=5000'
      args:
        chdir: /home/iloudaros/LoudVA/WorkerController
      environment:
        FLASK_ENV: production
      when: not WorkerController_running.stat.exists

    - name: Create the flags directory
      ansible.builtin.file:
        path: /tmp/ansible/flags
        state: directory
      when: not WorkerController_running.stat.exists

    - name: Create a flag file to indicate that Triton is running
      ansible.builtin.file:
        path: /tmp/ansible/flags/WorkerController_running.flag
        state: touch
      when: not WorkerController_running.stat.exists
      ignore_errors: yes

