---
- name: Stop WorkerController
  hosts: Workers
  become: yes
  gather_facts: no

  tasks:
    - shell: |
        screen -S WorkerController -X quit
      ignore_errors: yes

    - name: Delete WorkerController flag
      ansible.builtin.file:
        path: /tmp/ansible/flags/WorkerController_running.flag
        state: absent
      become: yes

      
