---
- name: Create Model Repository
  hosts: LoudJetsons

  tasks: 


    # Copy Model Repository to all worker nodes
    - name: Sending Initial Model Repository to Jetsons
      copy:
        src: /home/iloudaros/Loud_VA/model_repository
        dest: /home/iloudaros/tritonserver/model_repository

    # Download model repository in the tritonserver directory
    - name: Download model repository
      ansible.builtin.script: ../scripts/fetch_models.sh
      args:
        creates: /home/iloudaros/tritonserver/model_repository
        chdir: /home/iloudaros/tritonserver
      become: yes
