---
- name: Delete Triton From the System
  hosts: Workers

  tasks:
    
    # Delete the tgz file after extracting
    - name: Delete triton directory
      ansible.builtin.file:
        path: ~/tritonserver
        state: absent 
      become: yes

