---
- name: Performance Test
  hosts: LoudJetsons
  become: yes

  tasks: 
    - name: Run the Test
      ansible.builtin.shell: python3 Test_Performance.py >> logggg.txt
      args: 
        chdir: /home/iloudaros/LoudVA/tests


