---
- name: Performance Profiling
  hosts: LoudJetson0
  gather_facts: no
  become: yes

  tasks: 

    - name: Run the Python script for the performance measurements
      shell: sudo python3 /home/iloudaros/LoudVA/tests/Test_Performance.py > /home/iloudaros/LoudVA/measurements/Performance.log

    - name : Copy the log files from remote to local
      shell: (cd /home/iloudaros/LoudVA/measurements; find . -maxdepth 1 -type f) | cut -d'/' -f2
      register: files_to_copy

    - fetch: src=/home/iloudaros/LoudVA/measurements/{{ item }} dest=~/LoudVA/measurements
      with_items: "{{ files_to_copy.stdout_lines }}"
