---
- name: Performance Profiling
  hosts: Workers
  gather_facts: no
  become: yes

  tasks: 

    - name: Profiling --> Jetson Nano
      delegate_to: LoudJetson0
      run_once: true
      ignore_errors: yes
      block:
        - name: Run the Python script for the performance measurements
          shell: sudo python3 -u /home/iloudaros/LoudVA/tests/Test_Nano_Performance.py > /home/iloudaros/LoudVA/measurements/log 2>&1

        - name: Find files in remote directory recursively
          shell: find /home/iloudaros/LoudVA/measurements -type f
          register: files_to_fetch

        - name: Fetch each file individually
          fetch:
            src: "{{ item.path }}"
            dest: /home/louduser/LoudVA/measurements/{{ inventory_hostname }}/{{ item.path.split('/')[-1] }}
          loop: "{{ files_to_fetch.stdout_lines }}"

    - name: Profiling --> Jetson Xavier NX
      delegate_to: xavier-nx-00
      run_once: true
      ignore_errors: yes
      block:
        - debug:
            msg: "Running the Python script for the performance measurements on Jetson Xavier NX"

    - name: Profiling --> Jetson Xavier AGX
      delegate_to: agx-xavier-00 
      run_once: true
      ignore_errors: yes
      block:
        - debug:
            msg: "Running the Python script for the performance measurements on Jetson Xavier AGX"

      
      
