---
- name: Performance Profiling
  hosts: LoudJetson0, agx-xavier-00, xavier-nx-00
  gather_facts: no
  become: yes

  tasks: 
    - name: Run the Python script for the performance measurements
      shell: sudo python3 -u /home/iloudaros/LoudVA/tests/{{ performance_test }} > /home/iloudaros/LoudVA/measurements/log 2>&1

    - name: Compress measurements
      community.general.archive:
        path: /home/iloudaros/LoudVA/measurements
        dest: /home/iloudaros/LoudVA/measurements.tgz

    - name: Fetch the archive 
      fetch:
        src: /home/iloudaros/LoudVA/measurements.tgz
        dest: /home/louduser/LoudVA/measurements

    - name: Remove the archive
      file:
        path: /home/iloudaros/LoudVA/measurements.tgz
        state: absent

    - name: Unarchive Locally
      delegate_to: localhost
      unarchive:
        src: /home/louduser/LoudVA/measurements/{{ inventory_hostname }}/home/iloudaros/LoudVA/measurements.tgz
        dest: /home/louduser/LoudVA/measurements/{{ inventory_hostname }}

    - name: Remove the archive Locally
      delegate_to: localhost
      shell: rm -r /home/louduser/LoudVA/measurements/{{ inventory_hostname }}/home