---
- name: Start the Trtiton Server 
  hosts: LoudJetsons
  become: yes

  tasks: 
    - name: Run the shell script
      ansible.builtin.script: ../scripts/start_triton.sh
      args:
        creates: /ansible/flags/triton_running.flag

    - name: Leave a flag file
      ansible.builtin.file:
        path: /ansible/flags/triton_running.flag
        state: touch
      
