---
- name: Start the Trtiton Server #not working 
  hosts: LoudJetsons

  tasks: 
    - name: Sending The command to the Jetsons
      ansible.builtin.shell: cd /home/iloudaros/tritonserver/ && sudo ./bin/tritonserver --model-repository=./model_repository --backend-directory=./backends --backend-config=tensorflow,version=2
      become: yes