---
- name: Start the Trtiton Server 
  hosts: LoudJetsons
  gather_facts: no
  become: yes

  tasks: 
    - name: Run the shell script
      ansible.builtin.script: ../scripts/start_triton.sh
      args:
        creates: /tmp/ansible/flags/triton_running.flag

    - name: Create the flags directory
      ansible.builtin.file:
        path: /tmp/ansible/flags
        state: directory
      
    - name: Create the triton_running flag 
      ansible.builtin.file:
        path: /tmp/ansible/flags/triton_running.flag
        state: touch
      
