---
- name: Stop the Trtiton Server 
  hosts: LoudJetsons

  tasks: 
    - name: Sending The command to the Jetsons
      ansible.builtin.shell: pkill tritonserver
      args:
        removes: /ansible/flags/triton_running.flag
      become: yes

    - name: Delete triton flag
      ansible.builtin.file:
        path: /ansible/flags/triton.flag
        state: absent 
      become: yes