---

- name: Synchronize time with control node
  gather_facts: no  
  hosts: Workers
  
  
  tasks:
    # Get the current date from the local machine
    - name: Get control node date
      local_action: command date +%F
      register: control_node_date
      
    # Set the date on all worker nodes to the date of the control node
    - name: Set date on worker nodes
      shell: 'date +%F -s {{control_node_date.stdout}}'
      become: yes

      # Get the current time from the local machine
    - name: Get control node time
      local_action: command date +%T
      register: control_node_time
      
    # Set the time on all worker nodes to the time of the control node
    - name: Set time on worker nodes
      shell: 'date +%T -s {{control_node_time.stdout}}'
      become: yes

    # Print the time on all worker nodes
    - name: Print time on worker nodes
      shell: date
      become: yes
      register: worker_time
      
    - debug:
        var: worker_time.stdout