---
- name: Is the Triton server running?
  hosts: LoudJetsons
  gather_facts: no
  become: yes

  tasks: 
    - name: Check if there is a process named tritonserver running
      ansible.builtin.shell: ps -A | grep tritonserver
      register : tritonserver_process

    - debug:
        var: tritonserver_process.stdout_lines

    - name: Check if there is a flag file indicating that tritonserver is running
      ansible.builtin.shell: ls
      args:
        chdir: /ansible/flags
      register: tritonserver_flag

    - debug:
        var: tritonserver_flag.stdout_lines
      
