---
- name: Update Worker Nodes
  hosts: NX
  gather_facts: no
  become: yes 

  tasks: 


    # Git pull the LoudVA repository
    - name: Pulling the latest version of the LoudVA repository
      ansible.builtin.shell: git fetch && git reset --hard HEAD && git pull
      args:
        chdir: /home/iloudaros/LoudVA